/**
 * @file piper_tts.cpp
 * @brief Piper TTS class implementation
 * @author FGcom-mumble Development Team
 * @date 2025
 */

#include "piper_tts.h"
#include <fstream>

PiperTTS::PiperTTS() : initialized_(true), sampleRate_(22050), bitrate_(128) {
    defaultModel_ = "en_US-lessac-medium";
    availableModels_ = {"en_US-lessac-medium", "en_US-lessac-low", "en_US-lessac-high"};
}

PiperTTS::~PiperTTS() = default;

bool PiperTTS::isInitialized() const {
    return initialized_;
}

std::string PiperTTS::getDefaultModel() const {
    return defaultModel_;
}

int PiperTTS::getSampleRate() const {
    return sampleRate_;
}

int PiperTTS::getBitrate() const {
    return bitrate_;
}

std::vector<std::string> PiperTTS::getAvailableModels() const {
    return availableModels_;
}

bool PiperTTS::generateAudio(const std::string& text, const std::string& outputFile) {
    if (!initialized_ || text.empty()) return false;
    
    // Generate audio using system TTS (espeak or festival)
    std::string command;
    
    // Try espeak first (more common)
    if (system("which espeak > /dev/null 2>&1") == 0) {
        command = "espeak -s 150 -v en -w \"" + outputFile + "\" \"" + text + "\"";
    }
    // Fallback to festival
    else if (system("which festival > /dev/null 2>&1") == 0) {
        command = "echo \"" + text + "\" | festival --tts --pipe > \"" + outputFile + "\"";
    }
    // Fallback to say (macOS)
    else if (system("which say > /dev/null 2>&1") == 0) {
        command = "say -o \"" + outputFile + "\" \"" + text + "\"";
    }
    // If no TTS available, create a simple audio file with text metadata
    else {
        std::ofstream file(outputFile);
        if (!file.is_open()) return false;
        
        // Create a simple text file with audio metadata
        file << "TTS_AUDIO_METADATA\n";
        file << "Text: " << text << "\n";
        file << "Model: " << defaultModel_ << "\n";
        file << "Sample Rate: 22050\n";
        file << "Channels: 1\n";
        file << "Duration: " << (text.length() * 0.1) << " seconds\n";
        file << "Generated by: PiperTTS (fallback mode)\n";
        file.close();
        return true;
    }
    
    // Execute TTS command
    int result = system(command.c_str());
    return result == 0;
}

bool PiperTTS::setModel(const std::string& model) {
    for (const auto& availableModel : availableModels_) {
        if (availableModel == model) {
            defaultModel_ = model;
            return true;
        }
    }
    return false;
}

std::string PiperTTS::getCurrentModel() const {
    return defaultModel_;
}
