/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hbeni.fgcom_mumble.gui;

import hbeni.fgcom_mumble.Radio;
import hbeni.fgcom_mumble.radioGUI;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonModel;
import javax.swing.JButton;
import javax.swing.event.InternalFrameAdapter;
import javax.swing.event.InternalFrameEvent;

/**
 *
 * @author beni
 */
public class RadioInstance extends javax.swing.JInternalFrame {

    protected Radio radioBackend;
    
    /**
     * Creates new form RadioInstance
     */
    public RadioInstance(Radio r) {
        radioBackend = r;
        initComponents();
        jTextField_frqActive.setText(r.getFrequency());
        if (r.getFrequency() == "") {
            jTextField_frqSpare.setText("<Enter Frequency>");
        } else {
            jTextField_frqSpare.setText(r.getFrequency());
        }
        jSlider_txPWR.setValue(Math.round(r.getPower()));
        jSlider_volume.setValue(Math.round(r.getVolume()*100));
        jSlider_squelch.setValue(Math.round(r.getSquelch()*100));
        jToggleButton_ONOFF.setSelected(r.getPwrBtn());
        updateLabels();
        
        
        // Add a listener to detect closing
        addInternalFrameListener(new InternalFrameAdapter() {
            public void internalFrameClosing(InternalFrameEvent e) {
                radioGUI.deregisterRadio(r);
            }
        });
        
        this.setVisible(true);
    }
    
    /**
     * Update labels
     */
    public void updateLabels() {
        jLabel_squelch.setText(Float.toString(jSlider_squelch.getValue())+"%");
        jLabel_PWRVal.setText(Float.toString(jSlider_txPWR.getValue())+"W");
        jLabel_VolVal.setText(Float.toString(jSlider_volume.getValue())+"%");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField_frqActive = new javax.swing.JTextField();
        jTextField_frqSpare = new javax.swing.JTextField();
        jButton_swapFRQ = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSlider_volume = new javax.swing.JSlider();
        jSlider_txPWR = new javax.swing.JSlider();
        jLabel2 = new javax.swing.JLabel();
        jLabel_VolVal = new javax.swing.JLabel();
        jLabel_PWRVal = new javax.swing.JLabel();
        jButton_PTT = new javax.swing.JButton();
        jButton_ATIS = new javax.swing.JButton();
        jButton_Landline = new javax.swing.JButton();
        jSlider_squelch = new javax.swing.JSlider();
        jLabel3 = new javax.swing.JLabel();
        jLabel_squelch = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jToggleButton_ONOFF = new javax.swing.JToggleButton();

        setClosable(true);
        setMaximumSize(new java.awt.Dimension(600, 200));
        setMinimumSize(new java.awt.Dimension(600, 200));
        setPreferredSize(new java.awt.Dimension(600, 200));

        jTextField_frqActive.setEditable(false);
        jTextField_frqActive.setBackground(new java.awt.Color(224, 224, 224));
        jTextField_frqActive.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_frqActive.setText("FRQ_active");
        jTextField_frqActive.setToolTipText("The radio is currently tuned to this frequency");

        jTextField_frqSpare.setText("FRQ_spare");
        jTextField_frqSpare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_frqSpareActionPerformed(evt);
            }
        });

        jButton_swapFRQ.setText("<->");
        jButton_swapFRQ.setToolTipText("Swap Frequencies: Make the standby one active");
        jButton_swapFRQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_swapFRQActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel1.setText("Volume");

        jSlider_volume.setMajorTickSpacing(25);
        jSlider_volume.setMinorTickSpacing(5);
        jSlider_volume.setPaintTicks(true);
        jSlider_volume.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider_volumeStateChanged(evt);
            }
        });

        jSlider_txPWR.setMajorTickSpacing(25);
        jSlider_txPWR.setMaximum(500);
        jSlider_txPWR.setMinorTickSpacing(10);
        jSlider_txPWR.setPaintTicks(true);
        jSlider_txPWR.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider_txPWRStateChanged(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel2.setText("TX-PWR");

        jLabel_VolVal.setText("100");

        jLabel_PWRVal.setText("100");

        jButton_PTT.setText("PTT");
        jButton_PTT.setToolTipText("Press and hold to transmit");
        jButton_PTT.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jButton_PTTStateChanged(evt);
            }
        });

        jButton_ATIS.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        jButton_ATIS.setText("ATIS");
        jButton_ATIS.setToolTipText("Template: prepare ATIS-Recording template in standy FRQ field");
        jButton_ATIS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ATISActionPerformed(evt);
            }
        });

        jButton_Landline.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        jButton_Landline.setText("Landline");
        jButton_Landline.setToolTipText("Template: prepare landline template in standy FRQ field");
        jButton_Landline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LandlineActionPerformed(evt);
            }
        });

        jSlider_squelch.setMajorTickSpacing(10);
        jSlider_squelch.setMinorTickSpacing(5);
        jSlider_squelch.setPaintTicks(true);
        jSlider_squelch.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider_squelchStateChanged(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel3.setText("Squelch");

        jLabel_squelch.setText("100");

        jLabel4.setText("FRQ active");

        jLabel5.setText("FRQ standby");

        jToggleButton_ONOFF.setText("ON/OFF");
        jToggleButton_ONOFF.setToolTipText("Switch on (pressed) or off (depressed). ");
        jToggleButton_ONOFF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton_ONOFFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField_frqActive, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_swapFRQ))
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 171, Short.MAX_VALUE))
                            .addComponent(jTextField_frqSpare)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel_squelch))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel_VolVal))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel_PWRVal)))
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jSlider_volume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_ATIS, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_Landline)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jToggleButton_ONOFF))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSlider_txPWR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSlider_squelch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_PTT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_frqActive, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_frqSpare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_swapFRQ))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSlider_volume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel_VolVal))
                    .addComponent(jButton_ATIS)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton_Landline)
                        .addComponent(jToggleButton_ONOFF)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(jLabel_PWRVal))
                            .addComponent(jSlider_txPWR, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSlider_squelch, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel_squelch)
                                .addComponent(jLabel3)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jButton_PTT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_frqSpareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_frqSpareActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_frqSpareActionPerformed

    private void jButton_swapFRQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_swapFRQActionPerformed
        String swp = jTextField_frqSpare.getText();
        radioBackend.setFrequency(swp);
        
        jTextField_frqSpare.setText(jTextField_frqActive.getText());
        jTextField_frqActive.setText(swp);
        
    }//GEN-LAST:event_jButton_swapFRQActionPerformed

    private void jSlider_volumeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider_volumeStateChanged
        float v = (float)jSlider_volume.getValue();
        radioBackend.setVolume(v / 100);
        updateLabels();
    }//GEN-LAST:event_jSlider_volumeStateChanged

    private void jSlider_txPWRStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider_txPWRStateChanged
        float v = (float)jSlider_txPWR.getValue();
        radioBackend.setPower(v);
        updateLabels();
    }//GEN-LAST:event_jSlider_txPWRStateChanged

    private void jButton_ATISActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ATISActionPerformed
        // This is just a template button hiting the user
        jTextField_frqSpare.setText("RECORD_<tgt-frq-here>");
    }//GEN-LAST:event_jButton_ATISActionPerformed

    private void jButton_LandlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LandlineActionPerformed
        // This is just a template button hiting the user
        jTextField_frqSpare.setText("PHONE:<ICAO>:<POS>:<LINE>");
    }//GEN-LAST:event_jButton_LandlineActionPerformed

    private void jSlider_squelchStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider_squelchStateChanged
        float v = (float)jSlider_squelch.getValue();
        radioBackend.setSquelch(v / 100);
        updateLabels();
    }//GEN-LAST:event_jSlider_squelchStateChanged

    
    private void jButton_PTTStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jButton_PTTStateChanged
        JButton src = (JButton) evt.getSource();
        radioBackend.setPTT(src.getModel().isPressed());
    }//GEN-LAST:event_jButton_PTTStateChanged

    private void jToggleButton_ONOFFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton_ONOFFActionPerformed
        radioBackend.setPwrBtn(jToggleButton_ONOFF.isSelected());
    }//GEN-LAST:event_jToggleButton_ONOFFActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_ATIS;
    private javax.swing.JButton jButton_Landline;
    private javax.swing.JButton jButton_PTT;
    private javax.swing.JButton jButton_swapFRQ;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel_PWRVal;
    private javax.swing.JLabel jLabel_VolVal;
    private javax.swing.JLabel jLabel_squelch;
    private javax.swing.JSlider jSlider_squelch;
    private javax.swing.JSlider jSlider_txPWR;
    private javax.swing.JSlider jSlider_volume;
    private javax.swing.JTextField jTextField_frqActive;
    private javax.swing.JTextField jTextField_frqSpare;
    private javax.swing.JToggleButton jToggleButton_ONOFF;
    // End of variables declaration//GEN-END:variables
}
